--- #YAML:1.0
name:               Catalyst-Plugin-Log-Colorful
version:            0.13
abstract:           Catalyst Plugin for Colorful Log
author:
    - Tomohiro Teranishi <tomohiro.teranishi@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:         0
    Catalyst::Log:    0
    Data::Dumper:     0
    Term::ANSIColor:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
